pipeline {
    agent any
    stages {
        stage('Build Create and Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'p', usernameVariable: 'u')]) {
                   sh "docker build -f gotocloud-appointment-app-ui/Dockerfile --tag yantraqa/gotocloud-appointment-app-ui:latest gotocloud-appointment-app-ui"
                   sh "docker login --username $u --password $p"
                   sh "docker image push docker.io/yantraqa/gotocloud-appointment-app-ui:latest"
                }
            }
        }
    }
}